hello = """TCATCCGACGCCGAGGCTAATAGCAATTGACGTGGGTAGTACCTAGGGTAACATTACATG
GACCTCCTGTCGCACCTTTACTTCGCAGGGAGCTGCTTCGTACACGCGCTGTTCAGCCTA
AGTTTTCTGGCGCAGACTTACTCGGTTCGTCAGACCACCGTTATCGTGTTTATTAGTTTG
AGGAAATAGCTCCCTCGAAGTAGTGCAGTGCGGGGGCGAGCCAAACAAGGGGGCTCCGCG
CTACCTATTGTTCATTTCGGTGAGACAGTAACTAGTCGTTCGATAGCCGGCAAGCCTAAA
GCCTATTCGCAGTCCCATCAATAGGGGCATATGAATAGTTCCTGGGTTCCGTAAGTCCAG
ATTGCCCACAGGTACACTATTTAGTGCTGGGTGTGGTTGGTGCTCACTGCTTCTTGGGGC
ATGAAAGCGTATCCTTTTAACACTGTACGTGGAAGACTTTGAAACGGCCCTGCAGGCACT
ACTCGCGGTTGATAAAAGGCCGCGACGTAAAAAAACCATGTCAATTCGAACGAGGCACGA
TCACACCAATCATCTACTACGCCTGTATTAAACGGGAAAGGCACGGCCGAGGTAGAGTAC
TAGCTCCCAGTGGATACCGTTGAAGAGCGATTTAGTTACAAGATATTAACATTTGGGTAG
GTGGAGTCGTGTCAGTCTAACCCGCTGTCACGGTAGAAGTTGGATCGTAAAGTGAATGGA
ACACTCCCAGCCTTGCCTCAACCCGCATGATAGAAAAGATATCGAAGGGATAAAGCAGCT
AGGGGAGGATCAAGACTTTCTTGTGTCAAAACTCTTATCTTTGACCGCGATACTTCTGGA
TCGAGGATAGCTACTGGAGATATGTTACGGAGATTAGACGCCCGAAGATTTTTACAGTTT
CACTTTCCTTGTAGATTG"""
tally_c = 0
tally_g = 0
tally_a = 0
tally_t = 0
count = 0
for letter in hello:
     if letter == 'C':
          tally_c +=1
     if letter == 'G':
          tally_g +=1
     if letter == 'A':
          tally_a +=1
     if letter == 'T':
          tally_t +=1
     count +=1
print("total: " + str(count))
print("C: " + str(tally_c) + " G: " + str(tally_g) + " A: " + str(tally_a) + " T: " + str(tally_t))
percent_c = tally_c / count * 100
percent_g = tally_g / count * 100
percent_a = tally_a / count * 100
percent_t = tally_t / count * 100
print("A is {0:2.2f}% of the total, C is {1:2.2f}% of the total, G is {2:2.2f}% of the total and T is {3:2.2f}% of the total".format(percent_a, percent_c, percent_g, percent_t))
